<Font size=5> External Data Preprocessing

<font size=3>School Location

In [1]:
import pandas as pd
import geopandas as gpd

In [2]:
school_df_1819 = pd.read_csv('../data/raw/school_location_18_19.csv',encoding='cp1252')
school_df_20 = pd.read_csv('../data/raw/school_location_20.csv')
school_df_21 = pd.read_csv('../data/raw/school_location_21.csv',encoding='cp1252')

In [3]:
school_df_1819.head()

,Education_Sector,Entity_Type,School_No,School_Name,School_Type,School_Status,Address_Line_1,Address_Line_2,Address_Town,Address_State,...,Postal_Address_Line_1,Postal_Address_Line_2,Postal_Town,Postal_State,Postal_Postcode,Full_Phone_No,LGA_ID,LGA_Name,X,Y
0,Government,1,1,Alberton Primary School,Primary,O,21 Thomson Street,NaN,Alberton,VIC,...,21 Thomson Street,NaN,ALBERTON,VIC,3971,03 5183 2412,681,Wellington (S),146.666601,-38.617713
1,Government,1,3,Allansford and District Primary School,Primary,O,Frank Street,NaN,Allansford,VIC,...,Frank Street,NaN,ALLANSFORD,VIC,3277,03 5565 1382,673,Warrnambool (C),142.590393,-38.386281
2,Government,1,4,Avoca Primary School,Primary,O,118 Barnett Street,NaN,Avoca,VIC,...,P O Box 12,NaN,AVOCA,VIC,3467,03 5465 3176,599,Pyrenees (S),143.475649,-37.084502
3,Government,1,8,Avenel Primary School,Primary,O,40 Anderson Street,NaN,Avenel,VIC,...,40 Anderson Street,NaN,AVENEL,VIC,3664,03 5796 2264,643,Strathbogie (S),145.234722,-36.901368
4,Government,1,12,Warrandyte Primary School,Primary,O,5-11 Forbes Street,NaN,Warrandyte,VIC,...,5-11 Forbes Street,NaN,WARRANDYTE,VIC,3113,03 9844 3537,421,Manningham (C),145.213980,-37.742675

In [22]:
school_df_20.head()

,Education_Sector,Entity_Type,SCHOOL_NO,School_Name,School_Type,School_Status,Address_Line_1,Address_Line_2,Address_Town,Address_State,...,Postal_Address_Line_1,Postal_Address_Line_2,Postal_Town,Postal_State,Postal_Postcode,Full_Phone_No,LGA_ID,LGA_Name,X,Y
0,Government,1,1,Alberton Primary School,Primary,O,21 Thomson Street,NaN,Alberton,VIC,...,21 Thomson Street,NaN,ALBERTON,VIC,3971,03 5183 2412,681,Wellington (S),146.666601,-38.617713
1,Government,1,3,Allansford and District Primary School,Primary,O,Frank Street,NaN,Allansford,VIC,...,Frank Street,NaN,ALLANSFORD,VIC,3277,03 5565 1382,673,Warrnambool (C),142.590393,-38.386281
2,Government,1,4,Avoca Primary School,Primary,O,118 Barnett Street,NaN,Avoca,VIC,...,P O Box 12,NaN,AVOCA,VIC,3467,03 5465 3176,599,Pyrenees (S),143.475649,-37.084502
3,Government,1,8,Avenel Primary School,Primary,O,40 Anderson Street,NaN,Avenel,VIC,...,40 Anderson Street,NaN,AVENEL,VIC,3664,03 5796 2264,643,Strathbogie (S),145.234722,-36.901368
4,Government,1,12,Warrandyte Primary School,Primary,O,5-11 Forbes Street,NaN,Warrandyte,VIC,...,5-11 Forbes Street,NaN,WARRANDYTE,VIC,3113,03 9844 3537,421,Manningham (C),145.213980,-37.742675

In [23]:
school_df_21.head()

,Education_Sector,Entity_Type,SCHOOL_NO,School_Name,School_Type,School_Status,Address_Line_1,Address_Line_2,Address_Town,Address_State,...,Postal_Address_Line_1,Postal_Address_Line_2,Postal_Town,Postal_State,Postal_Postcode,Full_Phone_No,LGA_ID,LGA_Name,X,Y
0,Government,1,1,Alberton Primary School,Primary,O,21 Thomson Street,NaN,Alberton,VIC,...,21 Thomson Street,NaN,ALBERTON,VIC,3971,03 5183 2412,681,Wellington (S),146.666601,-38.617713
1,Government,1,3,Allansford and District Primary School,Primary,O,Frank Street,NaN,Allansford,VIC,...,Frank Street,NaN,ALLANSFORD,VIC,3277,03 5565 1382,673,Warrnambool (C),142.590393,-38.386281
2,Government,1,4,Avoca Primary School,Primary,O,118 Barnett Street,NaN,Avoca,VIC,...,P O Box 12,NaN,AVOCA,VIC,3467,03 5465 3176,599,Pyrenees (S),143.475649,-37.084502
3,Government,1,8,Avenel Primary School,Primary,O,40 Anderson Street,NaN,Avenel,VIC,...,40 Anderson Street,NaN,AVENEL,VIC,3664,03 5796 2264,643,Strathbogie (S),145.234722,-36.901368
4,Government,1,12,Warrandyte Primary School,Primary,O,5-11 Forbes Street,NaN,Warrandyte,VIC,...,5-11 Forbes Street,NaN,WARRANDYTE,VIC,3113,03 9844 3537,421,Manningham (C),145.213980,-37.742675

In [4]:
school_df_1819 = school_df_1819[['Education_Sector','School_Name','School_Type','Address_Line_1','Address_Town','Address_Postcode','LGA_Name','X','Y']]
school_df_20 = school_df_20[['Education_Sector','School_Name','School_Type','Address_Line_1','Address_Town','Address_Postcode','LGA_Name','X','Y']]
school_df_21 = school_df_21[['Education_Sector','School_Name','School_Type','Address_Line_1','Address_Town','Address_Postcode','LGA_Name','X','Y']]

In [5]:
school_df_1819.isnull().sum().sort_values(ascending=False)

Education_Sector    0
School_Name         0
School_Type         0
Address_Line_1      0
Address_Town        0
Address_Postcode    0
LGA_Name            0
X                   0
Y                   0
dtype: int64

In [6]:
school_df_20.isnull().sum().sort_values(ascending=False)

Education_Sector    0
School_Name         0
School_Type         0
Address_Line_1      0
Address_Town        0
Address_Postcode    0
LGA_Name            0
X                   0
Y                   0
dtype: int64

In [7]:
school_df_21.isnull().sum().sort_values(ascending=False)

Education_Sector    0
School_Name         0
School_Type         0
Address_Line_1      0
Address_Town        0
Address_Postcode    0
LGA_Name            0
X                   0
Y                   0
dtype: int64

In [8]:
school_df_1819.to_csv('../data/curated/school_df_1819_preprocessed.csv')
school_df_20.to_csv('../data/curated/school_df_20_preprocessed.csv')
school_df_21.to_csv('../data/curated/school_df_21_preprocessed.csv')

<Font size=3> Hospital Location

In [9]:
hospital_df= pd.read_csv('../data/raw/hospital_location.csv')
hospital_df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/hospital_location.csv'

In [14]:
hospital_df = hospital_df[['Formal Name','Emergency Capable','Location Address','Suburb','Postcode','Agency Type']]
hospital_df.head()

,Formal Name,Emergency Capable,Location Address,Suburb,Postcode,Agency Type
0,Albert Road Clinic,NO,31-33 Albert Road,South Melbourne,3205,Private Hospital
1,Albury Wodonga Health,YES,69 Vermont Street,Wodonga,3690,Public Hospital
2,"Albury Wodonga Health, Albury Campus",YES,Borella,Albury,2640,Public Hospital
3,Alexandra District Health,NO,20 Cooper Street,Alexandra,3714,Public Hospital
4,Alfred Health,NO,Commercial Road,Melbourne,3004,Public Hospital

In [15]:
hospital_df.isnull().sum().sort_values(ascending=False)

Formal Name          0
Emergency Capable    0
Location Address     0
Suburb               0
Postcode             0
Agency Type          0
dtype: int64

In [16]:
hospital_df.to_csv('../data/curated/hospital_preprocessed.csv')

<font size=3> Population Data

In [88]:
population_df=pd.read_excel('../data/raw/population.xlsx',sheet_name='Table 1')
population = population_df.loc[8:2461]
pop_drop = population.dropna(axis='columns',how = 'all')
pop_drop.to_csv('../data/raw/population_2.csv', encoding='utf-8')

In [89]:
pop_drop

,Australian Bureau of Statistics,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 25,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29,Unnamed: 30,Unnamed: 32,Unnamed: 33,Unnamed: 35,Unnamed: 36
8,1,New South Wales,1RNSW,Rest of NSW,101,Capital Region,10102,Queanbeyan,101021007,Braidwood,...,3950,4039,4140,4211,4273,4330,872,25.2,3418.4,1.3
9,1,New South Wales,1RNSW,Rest of NSW,101,Capital Region,10102,Queanbeyan,101021008,Karabar,...,8531,8526,8507,8488,8519,8546,-546,-6,7,1223.9
10,1,New South Wales,1RNSW,Rest of NSW,101,Capital Region,10102,Queanbeyan,101021009,Queanbeyan,...,11230,11355,11447,11450,11437,11370,655,6.1,4.8,2387.7
11,1,New South Wales,1RNSW,Rest of NSW,101,Capital Region,10102,Queanbeyan,101021010,Queanbeyan - East,...,4970,5013,5072,5117,5077,5093,142,2.9,13,391.7
12,1,New South Wales,1RNSW,Rest of NSW,101,Capital Region,10102,Queanbeyan,101021012,Queanbeyan West - Jerrabomberra,...,13150,13083,13008,12935,12796,12743,-480,-3.6,13.7,931.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2457,8,Australian Capital Territory,8ACTE,Australian Capital Territory,801,Australian Capital Territory,80111,Uriarra - Namadgi,801111141,Namadgi,...,39,45,50,56,61,67,26,63.4,1202.8,0.1
2458,9,Other Territories,9OTER,Other Territories,901,Other Territories,90101,Christmas Island,901011001,Christmas Island,...,1903,1877,1849,1801,1752,1716,-451,-20.8,136.1,12.6
2459,9,Other Territories,9OTER,Other Territories,901,Other Territories,90102,Cocos (Keeling) Islands,901021002,Cocos (Keeling) Islands,...,546,569,571,599,605,602,41,7.3,13.7,43.9
2460,9,Other Territories,9OTER,Other Territories,901,Other Territories,90103,Jervis Bay,901031003,Jervis Bay,...,402,392,376,360,338,310,-79,-20.3,67.2,4.6
2461,9,Other Territories,9OTER,Other Territories,901,Other Territories,90104,Norfolk Island,901041004,Norfolk Island,...,1757,1827,1920,1999,2096,2220,2220,0,38.7,57.4

In [90]:
population=pd.read_csv('../data/raw/population_2.csv',header=0,names=['S/T code','S/T name', 'GCCSA code', 'GCCSA name',\
                                                                      'SA4 code', 'SA4 name', 'SA3 code', 'SA3 name', 'SA2 code',\
                                                                      'SA2 name', '2001','2002', '2003','2004', '2005','2006',
                                                                      '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',\
                                                                      '2016','2017','2018', '2019','2020','2021','change 2011-2021 number','change 2011-2021 %',\
                                                                      'Area km2','population density 2021(persons/km2)'])
VIC_population = population.loc[population['S/T name']=='Victoria']

In [91]:
VIC_population

,S/T code,S/T name,GCCSA code,GCCSA name,SA4 code,SA4 name,SA3 code,SA3 name,SA2 code,SA2 name,...,2016,2017,2018,2019,2020,2021,change 2011-2021 number,change 2011-2021 %,Area km2,population density 2021(persons/km2)
650,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011001,Alfredton,...,11852,12639,13520,14408,15472,16823,8371,99.0,52.7,319.2
651,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011002,Ballarat,...,12301,12261,12237,12311,12183,12076,-289,-2.3,12.4,975.5
652,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011005,Buninyong,...,7311,7407,7413,7452,7369,7232,507,7.5,51.6,140.2
653,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011006,Delacombe,...,7195,7617,8174,8876,9736,10640,4802,82.3,34.2,311.5
654,2,Victoria,2RVIC,Rest of Vic.,201,Ballarat,20101,Ballarat,201011007,Smythes Creek,...,3990,4002,4040,4109,4148,4213,394,10.3,104.7,40.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1167,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21703,Colac - Corangamite,217031476,Otway,...,3556,3633,3707,3797,3905,3978,558,16.3,1505.9,2.6
1168,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041477,Moyne - East,...,6709,6714,6741,6790,6873,6989,210,3.1,3275.8,2.1
1169,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041478,Moyne - West,...,9603,9681,9773,9833,9842,9963,939,10.4,2037.8,4.9
1170,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041479,Warrnambool - North,...,21442,21676,21934,22157,22379,22462,2583,13.0,62.4,359.9
1171,2,Victoria,2RVIC,Rest of Vic.,217,Warrnambool and South West,21704,Warrnambool,217041480,Warrnambool - South,...,13173,13192,13214,13247,13323,13292,151,1.1,120.2,110.6

In [92]:
select_population = VIC_population.loc[:, ['S/T name', 'SA2 name', '2001','2002', '2003','2004', '2005','2006',\
                                           '2007', '2008', '2009', '2010', '2011', '2012', '2013', '2014', '2015',\
                                           '2016','2017','2018', '2019','2020','2021','change 2011-2021 number','change 2011-2021 %',\
                                           'Area km2','population density 2021(persons/km2)']]

In [93]:
select_population

,S/T name,SA2 name,2001,2002,2003,2004,2005,2006,2007,2008,...,2016,2017,2018,2019,2020,2021,change 2011-2021 number,change 2011-2021 %,Area km2,population density 2021(persons/km2)
650,Victoria,Alfredton,5756,6092,6293,6480,6648,6761,7034,7272,...,11852,12639,13520,14408,15472,16823,8371,99.0,52.7,319.2
651,Victoria,Ballarat,11497,11708,12015,12189,12269,12356,12408,12480,...,12301,12261,12237,12311,12183,12076,-289,-2.3,12.4,975.5
652,Victoria,Buninyong,5320,5399,5557,5620,5857,6037,6131,6252,...,7311,7407,7413,7452,7369,7232,507,7.5,51.6,140.2
653,Victoria,Delacombe,4154,4225,4371,4465,4704,5041,5206,5349,...,7195,7617,8174,8876,9736,10640,4802,82.3,34.2,311.5
654,Victoria,Smythes Creek,3317,3378,3411,3473,3508,3542,3594,3658,...,3990,4002,4040,4109,4148,4213,394,10.3,104.7,40.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1167,Victoria,Otway,3452,3479,3511,3511,3492,3459,3489,3501,...,3556,3633,3707,3797,3905,3978,558,16.3,1505.9,2.6
1168,Victoria,Moyne - East,6718,6704,6676,6643,6638,6652,6606,6631,...,6709,6714,6741,6790,6873,6989,210,3.1,3275.8,2.1
1169,Victoria,Moyne - West,8317,8387,8450,8487,8517,8601,8694,8792,...,9603,9681,9773,9833,9842,9963,939,10.4,2037.8,4.9
1170,Victoria,Warrnambool - North,17053,17449,17726,17937,18172,18528,18877,19107,...,21442,21676,21934,22157,22379,22462,2583,13.0,62.4,359.9
1171,Victoria,Warrnambool - South,12506,12578,12639,12697,12748,12792,12839,12903,...,13173,13192,13214,13247,13323,13292,151,1.1,120.2,110.6

In [94]:
postcode_SA2 = pd.read_csv('../data/raw/postcode_info.csv')
postcode_SA2

,Unnamed: 0,ID,Postcode,Locality,State,Longitude,Latitude,Category,Type,SA3,...,MMM 2015,MMM 2019,CED,Altitude,Charge Zone,PHN Code,PHN Name,LGA Region,Electorate,Electorate Rating
0,0,4746,3000,MELBOURNE,VIC,144.956776,-37.817403,Delivery Area,Delivery Area,20604.0,...,1.0,1.0,Melbourne,15.244751,V1,PHN201,North Western Melbourne,Melbourne,Melbourne,Inner Metropolitan
1,1,4747,3001,MELBOURNE,VIC,144.956776,-37.817403,Post Office Boxes,Post Office Boxes,20605.0,...,1.0,1.0,Melbourne,15.244751,V1,PHN203,NaN,Moonee Valley,Maribyrnong,NaN
2,2,4748,3002,EAST MELBOURNE,VIC,144.982207,-37.818517,Delivery Area,Delivery Area,20604.0,...,1.0,1.0,Melbourne,14.315022,V1,PHN201,North Western Melbourne,Yarra,Melbourne,Inner Metropolitan
3,3,4749,3003,WEST MELBOURNE,VIC,144.949592,-37.810871,Delivery Area,Delivery Area,20604.0,...,1.0,1.0,Melbourne,15.316063,V1,PHN201,North Western Melbourne,Melbourne,Melbourne,Inner Metropolitan
4,4,4750,3004,MELBOURNE,VIC,144.970161,-37.844246,Delivery Area,Delivery Area,20605.0,...,1.0,1.0,Macnamara,-3492.000000,V1,PHN203,South Eastern Melbourne,Yarra,Macnamara,Inner Metropolitan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3529,3529,11311,8111,MELBOURNE,VIC,144.970161,-37.844246,LVR,LVR,20605.0,...,1.0,1.0,NaN,NaN,V1,PHN203,NaN,Yarra,Macnamara,NaN
3530,3530,11312,8120,MELBOURNE,VIC,144.970161,-37.844246,LVR,LVR,20605.0,...,1.0,1.0,NaN,NaN,V1,PHN203,NaN,Yarra,Macnamara,NaN
3531,3531,11313,8205,MELBOURNE,VIC,144.970161,-37.844246,LVR,LVR,20605.0,...,1.0,1.0,NaN,NaN,V1,PHN203,NaN,Yarra,Macnamara,NaN
3532,3532,11331,8785,DANDENONG,VIC,145.208504,-38.016114,Post Office Boxes,Post Office Boxes,21204.0,...,1.0,1.0,NaN,15.138582,V1,PHN203,NaN,Monash,Isaacs,NaN
3533,3533,23878,9999,NORTH POLE,VIC,144.956776,-37.817403,Delivery Area,Delivery Area,20604.0,...,1.0,1.0,Melbourne,15.244751,NaN,NaN,NaN,Yarra,Macnamara,NaN

In [95]:
attribute = postcode_SA2.loc[:,['Postcode','Longitude','Latitude','SA2 NAME 2016']]
drop_dup = attribute.drop_duplicates(subset=['Postcode'])
drop_dup = drop_dup.drop_duplicates(subset=['Longitude','Latitude'])
rename = drop_dup.rename(columns={'SA2 NAME 2016':'SA2 name'})

In [96]:
rename

      Postcode   Longitude   Latitude        SA2 name
0         3000  144.956776 -37.817403       Melbourne
2         3002  144.982207 -37.818517  East Melbourne
3         3003  144.949592 -37.810871  West Melbourne
4         3004  144.970161 -37.844246       Southbank
7         3005  144.950858 -37.824608       Docklands
...        ...         ...        ...             ...
3512      8004  145.468994 -36.558800     Albert Park
3514      8006  144.959306 -37.809701       Melbourne
3517      8009  144.964531 -37.817201       Melbourne
3518      8010  146.293728 -38.185857          Romsey
3519      8011  144.961746 -37.811314       Melbourne

[724 rows x 4 columns]

In [99]:
merge_data = pd.DataFrame(pd.merge(rename, select_population, on='SA2 name', how='inner'))

In [101]:
merge_data.to_csv('../data/curated/population_postcode_SA2.csv')

In [100]:
merge_data

,Postcode,Longitude,Latitude,SA2 name,S/T name,2001,2002,2003,2004,2005,...,2016,2017,2018,2019,2020,2021,change 2011-2021 number,change 2011-2021 %,Area km2,population density 2021(persons/km2)
0,3002,144.982207,-37.818517,East Melbourne,Victoria,3731,3859,4243,4460,4495,...,5475,5495,5409,5413,5378,4962,-276,-5.3,2.9,1711.2
1,3005,144.950858,-37.824608,Docklands,Victoria,154,926,1913,3089,3779,...,11832,13923,15439,16375,16678,15942,9746,157.3,2.4,6522.9
2,3008,144.948039,-37.814719,Docklands,Victoria,154,926,1913,3089,3779,...,11832,13923,15439,16375,16678,15942,9746,157.3,2.4,6522.9
3,3010,144.961351,-37.796152,Parkville,Victoria,5332,5327,5253,5201,5157,...,7898,8182,8243,8294,8321,7446,895,13.7,4.0,1838.9
4,3050,144.954581,-37.800324,Parkville,Victoria,5332,5327,5253,5201,5157,...,7898,8182,8243,8294,8321,7446,895,13.7,4.0,1838.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
587,3990,145.501279,-38.455399,Wonthaggi - Inverloch,Victoria,17647,17801,17956,18117,18250,...,22577,23270,23966,24739,25631,26723,6327,31.0,728.8,36.7
588,3991,145.466781,-38.483041,Wonthaggi - Inverloch,Victoria,17647,17801,17956,18117,18250,...,22577,23270,23966,24739,25631,26723,6327,31.0,728.8,36.7
589,3992,145.534315,-38.569135,Wonthaggi - Inverloch,Victoria,17647,17801,17956,18117,18250,...,22577,23270,23966,24739,25631,26723,6327,31.0,728.8,36.7
590,3995,145.630713,-38.578071,Wonthaggi - Inverloch,Victoria,17647,17801,17956,18117,18250,...,22577,23270,23966,24739,25631,26723,6327,31.0,728.8,36.7
591,3996,145.745609,-38.629561,Wonthaggi - Inverloch,Victoria,17647,17801,17956,18117,18250,...,22577,23270,23966,24739,25631,26723,6327,31.0,728.8,36.7

In [1]:
merge_data["new"]=merge_data["2021"]*merge_data["change 2011-2021 %"]

NameError: name 'merge_data' is not defined

Park Location

In [2]:
sf = gpd.read_file("../data/raw/park/Parks_and_Open_Space.shp")
sf.head()

,OBJECTID,ParkID,Park_Name,Alias_Name,ParkClassC,BallDiamon,Concession,DogsOffLea,Horticultu,LawnBowlin,...,BallDiam_1,SportFie_1,TennisCo_1,DogsOffL_1,Trail1,LawnBowl_1,WaterView1,SHAPE_Leng,SHAPE_Area,geometry
0,1,150,Adanac Green,Adanac Green,GRN,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,127.841958,661.856354,"POLYGON ((475333.921 5364740.113, 475373.807 5..."
1,2,8,Bay Street Playground,Alexander Park,NP,None,None,Yes,None,None,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,318.093036,6450.126244,"POLYGON ((474547.427 5364639.236, 474624.025 5..."
2,3,1,Alston Green,Alston Green,GRN,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,215.293181,1913.354947,"POLYGON ((471701.394 5364472.539, 471676.758 5..."
3,4,2,Washington Avenue Park,Arbutus Park,NP,None,None,Yes,None,None,...,NaN,NaN,NaN,1.0,NaN,NaN,1.0,310.183085,4515.563500,"POLYGON ((471785.935 5365512.149, 471785.730 5..."
4,5,3,Arm Street Park,Arm Street Park,NP,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,238.816394,2766.329330,"POLYGON ((470993.251 5365489.545, 470981.300 5..."

In [3]:
# present the geometry using coordinate

sf['geometry'] = sf['geometry'].to_crs("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")
sf.head()

,OBJECTID,ParkID,Park_Name,Alias_Name,ParkClassC,BallDiamon,Concession,DogsOffLea,Horticultu,LawnBowlin,...,BallDiam_1,SportFie_1,TennisCo_1,DogsOffL_1,Trail1,LawnBowl_1,WaterView1,SHAPE_Leng,SHAPE_Area,geometry
0,1,150,Adanac Green,Adanac Green,GRN,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,127.841958,661.856354,"POLYGON ((-123.33348 48.43532, -123.33294 48.4..."
1,2,8,Bay Street Playground,Alexander Park,NP,None,None,Yes,None,None,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,318.093036,6450.126244,"POLYGON ((-123.34411 48.43438, -123.34307 48.4..."
2,3,1,Alston Green,Alston Green,GRN,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,215.293181,1913.354947,"POLYGON ((-123.38257 48.43276, -123.38290 48.4..."
3,4,2,Washington Avenue Park,Arbutus Park,NP,None,None,Yes,None,None,...,NaN,NaN,NaN,1.0,NaN,NaN,1.0,310.183085,4515.563500,"POLYGON ((-123.38150 48.44212, -123.38150 48.4..."
4,5,3,Arm Street Park,Arm Street Park,NP,None,None,None,None,None,...,NaN,NaN,NaN,NaN,NaN,NaN,1.0,238.816394,2766.329330,"POLYGON ((-123.39222 48.44188, -123.39237 48.4..."

In [15]:

park_name = list(sf['Park_Name'])
park_geo = list(sf['geometry'])

park_geo

[<shapely.geometry.polygon.Polygon at 0x7fa0e3c16fd0>,
 <shapely.geometry.polygon.Polygon at 0x7fa12823a5b0>,
 <shapely.geometry.polygon.Polygon at 0x7fa12e855730>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3c16fa0>,
 <shapely.geometry.polygon.Polygon at 0x7fa1283df4c0>,
 <shapely.geometry.polygon.Polygon at 0x7fa1283df460>,
 <shapely.geometry.polygon.Polygon at 0x7fa12e749c70>,
 <shapely.geometry.polygon.Polygon at 0x7fa1280a6eb0>,
 <shapely.geometry.polygon.Polygon at 0x7fa128307430>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3ca9af0>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3ca99d0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3ca9760>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3ca9dc0>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3ca9820>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3ca9b80>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3ca9940>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3ca9970>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3b40c40>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3b40b20>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b40bb0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b40eb0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b40d00>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b40f40>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b40790>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b40be0>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3b408e0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b40730>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b40d60>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b40370>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b40b80>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b40e50>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b40850>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b40dc0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b40d90>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3b40f10>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d1f0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d0d0>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3b8d070>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3b8d280>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d0a0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d1c0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d040>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d220>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d100>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d160>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d310>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d340>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d3a0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d370>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d3d0>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3b8d460>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d430>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d550>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d2b0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d4c0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d400>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d490>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3b8d5e0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d640>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d5b0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d700>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3b8d610>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d7f0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d850>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d820>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3b8d730>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d8e0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d4f0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d6a0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d790>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d880>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d760>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d910>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d940>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d9a0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d9d0>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3b8da30>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8da90>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8da00>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8db20>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d6d0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8d970>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8da60>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8db80>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8dbb0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8db50>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3b8dc40>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8dd30>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8dd60>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8ddc0>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3b8de20>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8ddf0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8dbe0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8dcd0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8dca0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8dd90>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8dc10>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8dc70>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8deb0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8de80>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8dee0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8df10>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8df70>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8df40>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8dfd0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8dfa0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8dac0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3b8de50>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3beb070>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3beb220>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb040>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb130>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3beb2e0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb190>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb280>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb250>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb2b0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb160>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb340>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3beb3a0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb370>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb400>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb490>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb1c0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb310>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb3d0>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3beb520>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb4f0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb580>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb610>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb4c0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb550>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb430>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3beb6a0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb790>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb7f0>,
 <shapely.geometry.multipolygon.MultiPolygon at 0x7fa0e3beb7c0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb5b0>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb640>,
 <shapely.geometry.polygon.Polygon at 0x7fa0e3beb880>]

In [14]:
# save the park's coordinate into a csv

park = {'Park_Name': list(sf['Park_Name']), 'Geometry': list(sf['geometry'])}

df_park = pd.DataFrame(park, columns=['Park_Name', 'Geometry'])
df_park.to_csv('../data/curated/park.csv')

In [9]:
import numpy as np
data = np.random.randn(3, 4)
data

array([[-1.32587924,  0.2864321 , -2.36485631, -0.10497695],
       [-1.0140295 , -0.93843088,  0.31584296, -0.1649103 ],
       [-1.72463784, -1.39731872, -0.14199401,  1.56319264]])